name: Ejecutar script DocuWare1

on:
  repository_dispatch:
    types: [webhook-disparado]
  workflow_dispatch:  # permite que se dispare desde la API

jobs:
  run-docuware-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script principal
        run: python main.py

